#!/usr/bin/zsh

feh --bg-fill --randomize ~/wallpaper/ &
unclutter -idle 1 -jitter 2 &
xset s off -dpms &

if grep -q ': wlp' <(ip link show); then
    nm-applet &
fi

if grep -q 'Elan Touchpad' <(xinput); then
    xinput set-prop "Elan Touchpad" "Synaptics Finger" 5 10 50
    xinput set-prop "Elan Touchpad" "Synaptics Tap Action" 2 3 0 0 1 3 2
fi
