#!/bin/bash

source /etc/skel/.bashrc

ulimit -c unlimited

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_MESSAGES=C
export LC_TIME=de_DE.UTF-8
export BROWSER=firefox
export EDITOR="vim"

function br()
{
  echo "$1" | sudo tee /sys/class/backlight/*/brightness
}

stm32_env()
{
  export PATH="/home/fh/x-tools/arm-unknown-eabi/bin:$PATH"
  export PREFIX=arm-unknown-eabi-
  export PLATFORM=bluepill
}

alias mpv='mpv --save-position-on-quit'
alias 7z='7z -bd'
alias ffmpeg='ffmpeg -hide_banner'
alias fpl='firefox -no-remote --profile .'
alias gdb='gdb -q'
alias gs='git log --oneline -3 && git status'
alias l='ls -la'
alias la='ls -la'
alias objdump='objdump -Mintel'
alias qr="qrencode -o - -t UTF8"
alias sss='sudo systemctl suspend'
alias whois='whois -H'
alias ymp3='youtube-dl --extract-audio --audio-format mp3'
alias st-ocd='openocd -f interface/stlink-v2.cfg -f target/stm32f1x.cfg'
