#!/bin/bash

ulimit -c unlimited

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_MESSAGES=C
export LC_TIME=de_DE.UTF-8
export BROWSER=firefox
export EDITOR="vim"

alias 7z='7z -bd'
alias ffmpeg='ffmpeg -hide_banner'
alias fpl='firefox -no-remote --profile .'
alias gdb='gdb -q'
alias gs='git log --oneline -3 && git status'
alias l='ls -la'
alias la='ls -la'
alias objdump='objdump -Mintel'
alias qr="qrencode -o - -t UTF8"
alias sss='sudo systemctl suspend'
alias whois='whois -H'
alias ymp3='youtube-dl --extract-audio --audio-format mp3'
